name: Crawl Articles
on: 
  push:
  schedule:
    # Update at 00:00, 04:00, 10:00, 14:00 of every day in UTC 
    - cron:  '*/30 * * * *'
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip lxml
        pip install -r requirements.txt

    - name: Start workers
      run: |
        python scripts/worker.py

    - name: Commit files
      run: |
        git config --local user.email "m18720841524@163.com"
        git config --local user.name "rssub"
        git add -A
        git commit -m "Update Articles"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
